import { Colors, Fonts } from '@constants/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
  },
  label: {
    fontFamily: Fonts.MANROPE_REGULAR,
    fontSize: 14,
    color: Colors.text.primary,
    marginBottom: 8,
  },
  iconContainer: {
    width: '100%',
    height: 56, 
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  input: {
    flex: 1,
    height: 56,
    backgroundColor: Colors.transparentWhite5,
    borderColor: Colors.gray50Transparent,
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 16,
    fontFamily: Fonts.MANROPE_REGULAR,
    fontSize: 16,
    lineHeight: 24,
    textAlignVertical: 'center',
    color: Colors.black,
  },
  inputError: {
    borderColor: Colors.error,
  },
  timeInput: {
    width: 100,
    height: 48,
    paddingVertical: 0,
    borderWidth: 1,
    borderRadius: 16,
    borderColor: Colors.grayLight,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 18,
    lineHeight: 48,
    fontFamily: Fonts.MANROPE_REGULAR,
    writingDirection: 'ltr',  
  },
  descriptionInput: {
    height: 100,
    fontSize: 14,
  },
  codeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
  },
  codeInput: {
    width: 56,
    height: 56,
    backgroundColor: Colors.transparentWhite5,
    borderColor: Colors.gray50Transparent,
    borderWidth: 1,
    borderRadius: 16,
    fontSize: 16,
    textAlign: 'center',
    color: Colors.black,
  },
  codeInputError: {
    borderColor: Colors.error,
  },
  codeInputSuccess: {
    borderColor: Colors.successBright,
  },
  errorBorder: {
    borderColor: Colors.error,
  },
  successBorder: {
    borderColor: Colors.successBright,
  },
  iconButton: {
    position: 'absolute',
    right: 15,
    padding: 5,
  },
  subText: {
    fontFamily: Fonts.MANROPE_REGULAR,
    fontSize: 12,
    color: Colors.grayMedium,
    marginTop: 5,
    textAlign: 'left',
  },
  subTextHighlighted: {
    color: Colors.orangeHighlight,
  },
  errorText: {
    fontFamily: Fonts.MANROPE_REGULAR,
    fontSize: 12,
    color: Colors.error,
    marginTop: 5,
    textAlign: 'left',
    alignSelf: 'flex-start',
  },
  strengthBarContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  strengthBar: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    marginHorizontal: 3,
  },
  codeInputFocused: {
    borderColor: Colors.text.primary,
    borderWidth: 2,
  },
  strengthBarInactive: {
    backgroundColor: Colors.border.light,
  },
  strengthBarActive: {
    backgroundColor: Colors.black,
  },
  weak: {
    backgroundColor: Colors.errorLight,
  },
  medium: {
    backgroundColor: Colors.warning,
  },
  strong: {
    backgroundColor: Colors.successMedium,
  },
  workTimeInput: {
    width: 70,
    height: 40,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderStyle: 'solid',
    borderColor: 'rgba(153, 153, 153, 0.5)',
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingVertical: 16,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    fontSize: 14,
    color: '#343434',
    fontFamily: 'Manrope-Regular',
  },
  timeRangeInlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    gap: 15,
  },
  timeRangeLabel: {
    fontSize: 14,
    fontWeight: 'bold',
    fontFamily: 'Manrope-SemiBold',
    color: 'rgba(153, 153, 153, 0.57)',
    textAlign: 'left',
  },
  timeRangeInput: {
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderStyle: 'solid',
    borderColor: 'rgba(153, 153, 153, 0.5)',
    borderWidth: 1,
    overflow: 'hidden',
    paddingHorizontal: 20,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    fontSize: 14,
    color: '#343434',
    fontFamily: 'Manrope-Regular',
  },
  timeRangeInputError: {
    borderColor: Colors.error,
  },
  timeRangeErrorText: {
    fontFamily: Fonts.MANROPE_REGULAR,
    fontSize: 12,
    color: Colors.error,
    marginTop: 5,
    textAlign: 'left',
    alignSelf: 'flex-start',
  },
});
